import Featured from "../layout/Featured"
import ImageSlider from "../layout/ImageSlider"
import ShipmentIcons from "../layout/ShipmentIcons"

function Home() {
  return (
    <div className="pt-14">
      <ImageSlider />
      <Featured />
      <ShipmentIcons />
      <h2 className="py-2 px-4">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Animi soluta temporibus delectus sequi, fugiat ea minus quos earum voluptatem nam mollitia aliquam laboriosam dolorum praesentium esse ut accusantium exercitationem aspernatur magnam voluptas odit. Earum ut repudiandae fuga expedita reiciendis voluptas tempora rerum ipsum impedit. Porro nesciunt deleniti quis numquam, incidunt atque consequuntur voluptatibus suscipit alias? Incidunt, alias officia porro similique ducimus odit amet corporis beatae explicabo fuga praesentium corrupti labore nam vitae nostrum. Fugiat omnis porro eaque molestias! Voluptates, porro in libero non ab culpa illum aut facilis. Voluptatem odio, beatae eos nihil debitis pariatur! Dolorem quis similique nobis beatae magni optio eveniet, architecto, quos et cum labore voluptas earum? Officia similique quam illo dolores totam aut tempora, animi doloremque sint cumque voluptatem eveniet pariatur placeat mollitia voluptas commodi suscipit corrupti atque eius adipisci reiciendis tenetur aliquid? Eius saepe, obcaecati quos soluta rerum esse at suscipit! Exercitationem praesentium possimus mollitia, quod, dolore ad vero voluptatibus qui ab animi aut hic, ex laborum. Natus repellat officia eius, nulla et tenetur nam aperiam corporis soluta voluptas similique reiciendis debitis, eaque labore. Omnis, distinctio? Earum vel iusto numquam incidunt cumque eius esse. Asperiores fugit voluptatibus quibusdam et repudiandae, non rem harum. Veniam soluta libero alias distinctio optio praesentium labore in laboriosam voluptatum enim, sit obcaecati, consequatur et! Vitae nam omnis pariatur iure esse quae adipisci praesentium incidunt! Sequi maxime deleniti inventore doloremque doloribus odit similique qui enim, harum blanditiis tempore fuga eum? Ipsam velit esse ullam, mollitia ut itaque suscipit cumque quis obcaecati sit aperiam consectetur optio consequuntur, odio odit fugit debitis? Labore perspiciatis eaque voluptate assumenda magni facere fugiat iusto corporis quod nihil, consequatur libero autem dolores provident, consequuntur ullam quisquam laudantium illo dolorem non! Quia laudantium non dolor doloribus quos, reiciendis consectetur totam. Ea, dolores. Eaque quae reiciendis nemo fugiat nihil!</h2>
        <h2>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Unde minus, sit blanditiis eaque illum modi omnis numquam voluptatem eos ipsum reprehenderit quis tempora assumenda in qui laudantium soluta, eum tempore quidem repudiandae dolores sint debitis magnam impedit? Debitis eum eveniet reprehenderit porro laboriosam numquam perferendis deleniti necessitatibus, nemo iusto minus dolor, repellendus ratione, placeat sit dolorem cupiditate similique aspernatur? Consectetur unde eaque, natus illum dolorem molestias impedit vitae, dolor dicta, ex voluptate in? Asperiores atque numquam, placeat iusto quisquam voluptates eum facilis eius nostrum ab veritatis hic recusandae illo ipsam quibusdam nihil fugit consequuntur. Rerum, natus! Cum magni pariatur, optio suscipit nulla quod officia rem voluptatum explicabo doloribus minima molestiae rerum, accusantium labore corporis ratione minus est iste. A totam cupiditate quibusdam impedit ipsa soluta harum quam, repudiandae saepe maxime fugiat asperiores quisquam possimus dolorum distinctio provident beatae perspiciatis nostrum omnis nobis voluptatum assumenda rerum quidem neque. Ipsum, tempore rerum. Impedit ipsa quaerat distinctio neque accusamus architecto quae aliquid soluta atque reprehenderit! Maiores, beatae distinctio. Beatae voluptates numquam soluta amet. Nesciunt vitae commodi nobis vel asperiores officia dolorum in quibusdam magni nostrum. Voluptatem architecto non inventore libero aspernatur soluta assumenda eveniet fuga eos ratione consequatur in aut quod, quos debitis neque ab nihil corporis. Corrupti aspernatur dolorem, quia natus atque inventore, possimus veniam autem facilis incidunt quos esse beatae quibusdam? Ab quas laborum officiis. Dolores aspernatur excepturi unde distinctio cupiditate eos, suscipit consequuntur harum fugit exercitationem neque recusandae ea, modi ab totam commodi nesciunt esse ad quos veritatis voluptate tempora fuga laboriosam. Saepe animi est libero vitae excepturi in mollitia enim, architecto nulla eum? Doloribus possimus blanditiis nihil itaque rem soluta, iure minus quibusdam ipsum repellat nam? Molestiae assumenda ullam aperiam ab nihil. At aut ratione reprehenderit iure perspiciatis. Architecto hic recusandae quibusdam voluptatem accusamus quia excepturi illum mollitia illo!</h2>
    </div>
  )
}
export default Home